import { Ban, Flag, ShieldCheck, Unlock } from 'lucide-react'
import type { BlockedProfile, MyCommunityReport } from '../lib/partyplay'
import { IdentityLabel, PlayerAvatar } from './SocialIdentity'

const reportLabel: Record<string, string> = { harassment: 'آزار و مزاحمت', spam: 'اسپم', cheating: 'تقلب', inappropriate_content: 'محتوای نامناسب', other: 'سایر' }
const reportState: Record<string, string> = { open: 'ثبت‌شده', reviewing: 'در حال بررسی', closed: 'بسته‌شده' }

export default function CommunitySafety({ blocks, reports, loading, busy, onUnblock }: { blocks: BlockedProfile[]; reports: MyCommunityReport[]; loading: boolean; busy: boolean; onUnblock: (userId: string) => Promise<void> }) {
  return <section className="panel community-safety-panel"><div className="section-panel-heading"><div><span className="eyebrow"><ShieldCheck size={15}/> ایمنی جامعه</span><h2>کنترل ارتباطات و گزارش‌ها</h2><p>مسدودسازی، دوستی و دعوت‌های در انتظار را قطع می‌کند؛ اطلاعات گزارش برای دیگران نمایش داده نمی‌شود.</p></div></div><div className="safety-section"><div className="safety-section-title"><span><Ban size={15}/> حساب‌های مسدودشده</span><small>{blocks.length}</small></div>{loading ? <p className="safety-muted">در حال همگام‌سازی…</p> : blocks.length ? <div className="safety-person-list">{blocks.map((person) => <article key={person.id}><PlayerAvatar seed={person.avatar_seed} label={person.display_name} size="sm" status={person.presence}/><div><IdentityLabel label={person.display_name} isVerified={person.is_verified} membershipTier={person.membership_tier} siteRole={person.site_role} compact/><small dir="ltr">@{person.username}</small></div><button className="secondary-button safety-unblock" disabled={busy} onClick={() => void onUnblock(person.id)}><Unlock size={14}/>رفع مسدودسازی</button></article>)}</div> : <p className="safety-muted">هیچ حسابی را مسدود نکرده‌ای.</p>}</div><div className="safety-section"><div className="safety-section-title"><span><Flag size={15}/> گزارش‌های من</span><small>{reports.length}</small></div>{reports.length ? <div className="safety-report-list">{reports.slice(0, 6).map((report) => <article key={report.id}><div><strong>{reportLabel[report.category] || report.category}</strong><small>دربارهٔ {report.target_display_name}</small></div><span className={`safety-report-state state-${report.status}`}>{reportState[report.status] || report.status}</span></article>)}</div> : <p className="safety-muted">هنوز گزارشی ثبت نکرده‌ای.</p>}</div></section>
}
