import { useEffect, useMemo, useRef, useState, type CSSProperties, type PointerEvent } from 'react'
import { Bot, Dice5, RefreshCw, RotateCcw, Sparkles, Users } from 'lucide-react'
import type { GameDefinition } from '../data/gameCatalog'

const locations = ['کافهٔ دنج', 'متروی تهران', 'استادیوم آزادی', 'سینمای قدیمی', 'فرودگاه مهرآباد', 'بازار بزرگ', 'ساحل کیش', 'کتابخانهٔ ملی']
const drawWords = ['دوچرخه', 'گربهٔ فضانورد', 'هندوانه', 'قلعه', 'بادبادک', 'چای ایرانی', 'اتوبوس', 'کوه دماوند']
const codeWords = ['باران','دریا','مداد','شاهین','کوه','پرتقال','سفر','پنجره','پل','نقشه','آتش','ساعت','دریاچه','چراغ','کلاه','آینه','آسمان','رویا','سکه','قایق','دود','گل','کلید','شب','صدا']
const suits = ['♠','♥','♦','♣']
const ranks = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']
const card = () => `${ranks[Math.floor(Math.random() * ranks.length)]}${suits[Math.floor(Math.random() * suits.length)]}`
const roll = () => Math.floor(Math.random() * 6) + 1
const pause = 520

export default function OpenSourceArcade({ game, onBack }: { game: GameDefinition; onBack: () => void }) {
  const scene = game.id === 'connect-four' ? <ConnectFour/> : game.id === 'ludo' ? <Ludo/> : game.id === 'snakes' ? <Snakes/> : game.id === 'spyfall' ? <Spyfall/> : game.id === 'uno' ? <Uno/> : game.id === 'pictionary' ? <Pictionary/> : game.id === 'codenames' ? <Codenames/> : game.id === 'backgammon' ? <Backgammon/> : <Hokm/>
  return <section className={`arcade-game accent-${game.accent}`}><header className="arcade-header"><button className="back-link" onClick={onBack}>خانه</button><div><span className="eyebrow">بازی با ربات پارتی پلی</span><h1>{game.title}</h1><p>{game.subtitle}</p></div><span className="arcade-source"><Bot size={15}/>حریف ربات</span></header><div className="arcade-surface">{scene}</div></section>
}

const drop = (board: (null|'a'|'b')[], col: number, mark: 'a'|'b') => { const next = [...board]; for (let row = 5; row >= 0; row--) { const index = row * 7 + col; if (!next[index]) { next[index] = mark; return next } } return null }
const connectWin = (board: (null|'a'|'b')[], mark: 'a'|'b') => { for (let r = 0; r < 6; r++) for (let c = 0; c < 7; c++) for (const [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]]) if (board[r*7+c] === mark && [1,2,3].every(step => r+dr*step >= 0 && r+dr*step < 6 && c+dc*step >= 0 && c+dc*step < 7 && board[(r+dr*step)*7+c+dc*step] === mark)) return true; return false }
function ConnectFour() { const [board,setBoard]=useState<(null|'a'|'b')[]>(Array(42).fill(null)); const [botTurn,setBotTurn]=useState(false); const [note,setNote]=useState('نوبت توست؛ یک ستون را انتخاب کن.'); const [over,setOver]=useState(false); const play=(col:number)=>{if(botTurn||over)return;const next=drop(board,col,'a');if(!next)return;setBoard(next);if(connectWin(next,'a')){setNote('چهار مهره کنار هم؛ تو بردی!');setOver(true)}else{setBotTurn(true);setNote('ربات در حال انتخاب ستون است…')}};useEffect(()=>{if(!botTurn)return;const timer=window.setTimeout(()=>{setBoard(old=>{const options=Array.from({length:7},(_,col)=>col).filter(col=>drop(old,col,'b'));const winning=options.find(col=>{const candidate=drop(old,col,'b');return candidate&&connectWin(candidate,'b')});const next=drop(old,winning ?? options[Math.floor(Math.random()*options.length)],'b') || old;if(connectWin(next,'b')){setNote('ربات چهار مهره کنار هم چید.');setOver(true)}else setNote('نوبت توست؛ یک ستون را انتخاب کن.');return next});setBotTurn(false)},pause);return()=>window.clearTimeout(timer)},[botTurn]);return <div className="arcade-center"><p className="arcade-message">{note}</p><div className="connect-board">{board.map((cell,index)=><button key={index} onClick={()=>play(index%7)} disabled={botTurn||over} className={`connect-slot ${cell||''}`} aria-label={`ستون ${index%7+1}`}/>)}</div>{over&&<button className="secondary-button" onClick={()=>{setBoard(Array(42).fill(null));setOver(false);setNote('نوبت توست؛ یک ستون را انتخاب کن.')}}><RefreshCw size={16}/>دور تازه</button>}</div> }

function Ludo(){const [you,setYou]=useState(0);const [bots,setBots]=useState([0,0,0]);const [thinking,setThinking]=useState(false);const [note,setNote]=useState('تاس را بینداز و قبل از ربات‌ها به خانه برس.');const play=()=>{if(thinking||you>=56)return;const d=roll();setYou(value=>Math.min(56,value+d));setThinking(true);setNote(`تاس تو ${d} شد؛ ربات‌ها حرکت می‌کنند…`)};useEffect(()=>{if(!thinking)return;const timer=window.setTimeout(()=>{setBots(values=>values.map(value=>Math.min(56,value+roll())));setThinking(false);setNote('نوبت توست؛ تاس را بینداز.')},pause);return()=>window.clearTimeout(timer)},[thinking]);const colors=['red','blue','green','gold'];return <div className="arcade-center"><div className="ludo-track"><div className="ludo-token red" style={{'--step':you} as CSSProperties}><b>تو</b><span>{you}/۵۶</span></div>{bots.map((position,index)=><div className={`ludo-token ${colors[index+1]}`} key={index} style={{'--step':position} as CSSProperties}><b>ر{index+1}</b><span>{position}/۵۶</span></div>)}</div><p className="arcade-message">{you>=56?'تو برنده شدی!':note}</p><button className="primary-button" onClick={play} disabled={thinking||you>=56}><Dice5 size={18}/>تاس من</button></div>}

function Snakes(){const [you,setYou]=useState(1);const [bot,setBot]=useState(1);const [thinking,setThinking]=useState(false);const ladders:Record<number,number>={4:14,9:31,20:38,28:84,40:59,51:67,71:91};const snakes:Record<number,number>={17:7,54:34,62:19,87:36,93:73};const step=(value:number)=>{const d=roll(),raw=Math.min(100,value+d);return ladders[raw]||snakes[raw]||raw};const play=()=>{if(thinking||you>=100||bot>=100)return;setYou(step);setThinking(true)};useEffect(()=>{if(!thinking)return;const timer=window.setTimeout(()=>{setBot(step);setThinking(false)},pause);return()=>window.clearTimeout(timer)},[thinking]);return <div className="arcade-center"><div className="snake-mini-board">{Array.from({length:100},(_,index)=>{const cell=100-index;return <span key={cell} className={`${cell===you?'snake-player':''} ${cell===bot?'snake-bot':''}`}>{cell===you&&cell===bot?'◉':cell===you?'ت':cell===bot?'ر':' '}</span>})}</div><p className="arcade-message">تو: {you} / ربات: {bot} — {you>=100?'تو برنده شدی!':bot>=100?'ربات برنده شد؛ دوباره تلاش کن.':thinking?'ربات تاس می‌اندازد…':'نوبت توست.'}</p><button className="primary-button" onClick={play} disabled={thinking||you>=100||bot>=100}><Dice5 size={18}/>تاس من</button></div>}

function Spyfall(){const [location,setLocation]=useState(locations[0]);const [shown,setShown]=useState(false);const [question,setQuestion]=useState('ربات: یک سؤال بپرس تا مطمئن شوی طرف مقابل مکان را می‌شناسد.');const refresh=()=>{setLocation(locations[Math.floor(Math.random()*locations.length)]);setShown(false);setQuestion('ربات: دور بعد، سؤال‌های دقیق‌تری بپرس.')};return <div className="arcade-center spyfall-stage"><span className="role-orb">?</span><h2>{shown?`مکان تو: ${location}`:'کارت نقش محرمانه'}</h2><p>{question}</p><button className="primary-button" onClick={()=>setShown(value=>!value)}>{shown?'پنهان‌کردن کارت':'نمایش کارت من'}</button><button className="secondary-button" onClick={()=>setQuestion(['ربات: آنجا معمولاً چه صدایی می‌شنوی؟','ربات: برای ورود چه چیزی لازم است؟','ربات: اگر دیر برسی، چه می‌شود؟'][Math.floor(Math.random()*3)])}><Bot size={16}/>سؤال ربات</button><button className="text-button" onClick={refresh}><RotateCcw size={15}/>دور تازه</button></div>}

function Uno(){const [hand,setHand]=useState(()=>Array.from({length:7},card));const [top,setTop]=useState(card());const [botCount,setBotCount]=useState(7);const [thinking,setThinking]=useState(false);const [note,setNote]=useState('ورق هم‌رنگ یا هم‌عدد را بازی کن.');const play=(current:string)=>{if(thinking)return;if(current[0]===top[0]||current.at(-1)===top.at(-1)){setTop(current);setHand(values=>values.filter(value=>value!==current));setThinking(true);setNote('ربات در حال انتخاب ورق است…')}else setNote('این ورق با کارت زمین جور نیست.')};useEffect(()=>{if(!thinking)return;const timer=window.setTimeout(()=>{setTop(card());setBotCount(value=>Math.max(0,value-1));setThinking(false);setNote('ربات بازی کرد؛ نوبت توست.')},pause);return()=>window.clearTimeout(timer)},[thinking]);return <div className="arcade-center uno-stage"><div className="uno-card top-card">{top}</div><p className="arcade-message">ورق‌های ربات: {botCount} — {note}</p><div className="uno-hand">{hand.map((current,index)=><button className="uno-card" key={`${current}${index}`} onClick={()=>play(current)} disabled={thinking}>{current}</button>)}</div><button className="secondary-button" disabled={thinking} onClick={()=>{setHand(values=>[...values,card()]);setThinking(true);setNote('یک ورق کشیدی؛ نوبت ربات است…')}}>یک ورق بکش</button></div>}

function Pictionary(){const canvas=useRef<HTMLCanvasElement>(null);const [word,setWord]=useState(drawWords[0]);const [drawing,setDrawing]=useState(false);const [note,setNote]=useState('ربات منتظر نقاشی توست.');const paint=(event:PointerEvent<HTMLCanvasElement>)=>{if(!drawing)return;const element=canvas.current;if(!element)return;const rect=element.getBoundingClientRect(),context=element.getContext('2d')!;context.lineWidth=6;context.lineCap='round';context.lineTo(event.clientX-rect.left,event.clientY-rect.top);context.stroke();context.beginPath();context.moveTo(event.clientX-rect.left,event.clientY-rect.top)};const clear=()=>canvas.current?.getContext('2d')?.clearRect(0,0,680,360);return <div className="arcade-center draw-stage"><p className="arcade-message">کلمهٔ این دور: <b>{word}</b> — {note}</p><canvas ref={canvas} width="680" height="360" className="drawing-canvas" onPointerDown={event=>{setDrawing(true);paint(event)}} onPointerMove={paint} onPointerUp={()=>{setDrawing(false);canvas.current?.getContext('2d')?.beginPath()}}/><div className="inline-actions"><button className="secondary-button" onClick={clear}>پاک‌کردن</button><button className="secondary-button" onClick={()=>setNote(Math.random()>.45?`ربات حدس زد: «${word}» — درست بود!`:'ربات هنوز مطمئن نیست؛ جزئیات بیشتری بکش.')}><Bot size={16}/>حدس ربات</button><button className="primary-button" onClick={()=>{clear();setWord(drawWords[Math.floor(Math.random()*drawWords.length)]);setNote('کلمهٔ تازه رسید.')}}><Sparkles size={16}/>کلمهٔ بعدی</button></div></div>}

function Codenames(){const [revealed,setRevealed]=useState<number[]>([]);const [thinking,setThinking]=useState(false);const words=useMemo(()=>[...codeWords].sort(()=>Math.random()-.5),[]);const select=(index:number)=>{if(thinking||revealed.includes(index))return;setRevealed(values=>[...values,index]);setThinking(true)};useEffect(()=>{if(!thinking)return;const timer=window.setTimeout(()=>{setRevealed(values=>{const options=words.map((_,index)=>index).filter(index=>!values.includes(index));return options.length?[...values,options[Math.floor(Math.random()*options.length)]]:values});setThinking(false)},pause);return()=>window.clearTimeout(timer)},[thinking,words]);return <div className="arcade-center"><p className="arcade-message">{thinking?'ربات در حال انتخاب کارت است…':'یک کارت انتخاب کن؛ سپس ربات پاسخ می‌دهد.'}</p><div className="code-grid">{words.map((word,index)=><button className={`code-card ${revealed.includes(index)?index%5===0?'assassin':'revealed':''}`} key={`${word}-${index}`} onClick={()=>select(index)} disabled={thinking||revealed.includes(index)}>{word}</button>)}</div></div>}

function Backgammon(){const [you,setYou]=useState(0);const [bot,setBot]=useState(0);const [dice,setDice]=useState<[number,number]>([1,1]);const [thinking,setThinking]=useState(false);const play=()=>{if(thinking)return;const next:[number,number]=[roll(),roll()];setDice(next);setYou(value=>Math.min(15,value+next[0]));setThinking(true)};useEffect(()=>{if(!thinking)return;const timer=window.setTimeout(()=>{setBot(value=>Math.min(15,value+roll()));setThinking(false)},pause);return()=>window.clearTimeout(timer)},[thinking]);return <div className="arcade-center"><div className="backgammon-board">{Array.from({length:24},(_,index)=><span key={index} className={index<you?'checker-a':index>23-bot?'checker-b':''}>{index+1}</span>)}</div><p className="arcade-message">تاس تو: {dice[0]} و {dice[1]} — تو: {you}/۱۵ · ربات: {bot}/۱۵</p><button className="primary-button" onClick={play} disabled={thinking||you>=15||bot>=15}><Dice5 size={18}/>تاس من</button></div>}

function Hokm(){const [trump,setTrump]=useState('♥');const [hand,setHand]=useState(()=>Array.from({length:13},card));const [you,setYou]=useState(0);const [bot,setBot]=useState(0);const [thinking,setThinking]=useState(false);const play=(current:string)=>{if(thinking)return;setHand(values=>values.filter(value=>value!==current));setYou(value=>value+1);setThinking(true)};useEffect(()=>{if(!thinking)return;const timer=window.setTimeout(()=>{setBot(value=>value+1);setThinking(false)},pause);return()=>window.clearTimeout(timer)},[thinking]);return <div className="arcade-center hokm-stage"><p className="arcade-message">حکم: <b className="trump">{trump}</b> — دست‌های تو: {you} · ربات: {bot}</p><div className="uno-hand">{hand.map((current,index)=><button className="uno-card" key={`${current}${index}`} onClick={()=>play(current)} disabled={thinking}>{current}</button>)}</div><div className="inline-actions">{suits.map(suit=><button className="secondary-button" key={suit} onClick={()=>setTrump(suit)}>{suit}</button>)}</div><p className="observer-note"><Users size={15}/>تمرین دونفره با ربات؛ در اتاق دوستان، قانون چهار‌نفره اجرا می‌شود.</p></div>}
