import { useMemo, useRef, useState, type CSSProperties, type PointerEvent } from 'react'
import { Dice5, RefreshCw, RotateCcw, Sparkles, Users } from 'lucide-react'
import type { GameDefinition } from '../data/gameCatalog'

const locations = ['کافهٔ دنج', 'متروی تهران', 'استادیوم آزادی', 'سینمای قدیمی', 'فرودگاه مهرآباد', 'بازار بزرگ', 'ساحل کیش', 'کتابخانهٔ ملی']
const drawWords = ['دوچرخه', 'گربهٔ فضانورد', 'هندوانه', 'قلعه', 'بادبادک', 'چای ایرانی', 'اتوبوس', 'کوه دماوند']
const codeWords = ['باران','دریا','مداد','شاهین','کوه','پرتقال','سفر','پنجره','پل','نقشه','آتش','ساعت','دریاچه','چراغ','کلاه','آینه','آسمان','رویا','سکه','قایق','دود','گل','کلید','شب','صدا']
const suits = ['♠','♥','♦','♣']
const ranks = ['A','2','3','4','5','6','7','8','9','10','J','Q','K']
const card = () => `${ranks[Math.floor(Math.random() * ranks.length)]}${suits[Math.floor(Math.random() * suits.length)]}`
const roll = () => Math.floor(Math.random() * 6) + 1

export default function OpenSourceArcade({ game, onBack }: { game: GameDefinition; onBack: () => void }) {
  return <section className={`arcade-game accent-${game.accent}`}><header className="arcade-header"><button className="back-link" onClick={onBack}>خانه</button><div><span className="eyebrow">بازی تازهٔ پارتی پلی</span><h1>{game.title}</h1><p>{game.subtitle}</p></div><span className="arcade-source">{game.players} · {game.duration}</span></header><div className="arcade-surface">{game.id === 'connect-four' ? <ConnectFour/> : game.id === 'ludo' ? <Ludo/> : game.id === 'snakes' ? <Snakes/> : game.id === 'spyfall' ? <Spyfall/> : game.id === 'uno' ? <Uno/> : game.id === 'pictionary' ? <Pictionary/> : game.id === 'codenames' ? <Codenames/> : game.id === 'backgammon' ? <Backgammon/> : <Hokm/>}</div></section>
}

function ConnectFour() { const [board,setBoard]=useState<(null|'a'|'b')[]>(Array(42).fill(null)); const [turn,setTurn]=useState<'a'|'b'>('a'); const [message,setMessage]=useState('نوبت توست؛ ستونی را انتخاب کن.'); const drop=(col:number)=>{ for(let row=5;row>=0;row--){ const i=row*7+col; if(!board[i]){ const n=[...board]; n[i]=turn; setBoard(n); setTurn(turn==='a'?'b':'a'); setMessage(turn==='a'?'نوبت آبی است.':'نوبت قرمز است.'); return } } }; return <div className="arcade-center"><p className="arcade-message">{message}</p><div className="connect-board">{board.map((cell,i)=><button key={i} onClick={()=>drop(i%7)} className={`connect-slot ${cell||''}`} aria-label={`ستون ${i%7+1}`}/>)}</div><button className="secondary-button" onClick={()=>{setBoard(Array(42).fill(null));setTurn('a');setMessage('دور تازه شروع شد.')}}><RefreshCw size={16}/>دور تازه</button></div> }
function Ludo(){ const [pos,setPos]=useState([0,0,0,0]); const [turn,setTurn]=useState(0); const [last,setLast]=useState<number|null>(null); const colors=['red','blue','green','gold']; const play=()=>{const d=roll();setLast(d);setPos(p=>p.map((v,i)=>i===turn?Math.min(56,v+d):v));setTurn(t=>(t+1)%4)}; return <div className="arcade-center"><div className="ludo-track">{pos.map((p,i)=><div className={`ludo-token ${colors[i]}`} key={i} style={{'--step':p} as CSSProperties}><b>{i+1}</b><span>{p}/۵۶</span></div>)}</div><p className="arcade-message">نوبت بازیکن {turn+1} است {last ? `— تاس: ${last}` : ''}</p><button className="primary-button" onClick={play}><Dice5 size={18}/>تاس بریز</button></div> }
function Snakes(){const [p,setP]=useState(1);const [d,setD]=useState<number|null>(null);const climbs:Record<number,number>={4:14,9:31,20:38,28:84,40:59,51:67,71:91};const falls:Record<number,number>={17:7,54:34,62:19,87:36,93:73};const play=()=>{const n=roll();let next=Math.min(100,p+n);next=climbs[next]||falls[next]||next;setD(n);setP(next)};return <div className="arcade-center"><div className="snake-mini-board">{Array.from({length:100},(_,i)=><span key={i} className={p===100-i?'snake-player':''}>{100-i}</span>)}</div><p className="arcade-message">موقعیت مهره: {p} {d?`— تاس: ${d}`:''}</p><button className="primary-button" onClick={play}><Dice5 size={18}/>تاس بریز</button></div>}
function Spyfall(){const [location,setLocation]=useState(()=>locations[Math.floor(Math.random()*locations.length)]);const [spy,setSpy]=useState(Math.ceil(Math.random()*6));const [revealed,setRevealed]=useState(false);const reset=()=>{setLocation(locations[Math.floor(Math.random()*locations.length)]);setSpy(Math.ceil(Math.random()*6));setRevealed(false)};return <div className="arcade-center spyfall-stage"><span className="role-orb">?</span><h2>{revealed?`مکان: ${location}`:'کارت نقش محرمانه'}</h2><p>{revealed?`بازیکن ${spy} جاسوس است؛ با سؤال‌های هوشمندانه پیدایش کنید.`:'کارت را فقط به نوبت بازیکن‌ها نشان دهید.'}</p><button className="primary-button" onClick={()=>setRevealed(v=>!v)}>{revealed?'پنهان‌کردن کارت':'نمایش کارت'}</button><button className="text-button" onClick={reset}><RotateCcw size={15}/>دور تازه</button></div>}
function Uno(){const [hand,setHand]=useState(()=>Array.from({length:7},card));const [top,setTop]=useState(card());const [note,setNote]=useState('ورق هم‌رنگ یا هم‌عدد را بازی کن.');const play=(c:string)=>{if(c[0]===top[0]||c.at(-1)===top.at(-1)){setTop(c);setHand(h=>h.filter(x=>x!==c));setNote('حرکت درست بود.')}else setNote('این ورق با کارت زمین جور نیست.');};return <div className="arcade-center uno-stage"><div className="uno-card top-card">{top}</div><p className="arcade-message">{note}</p><div className="uno-hand">{hand.map((c,i)=><button className="uno-card" key={`${c}${i}`} onClick={()=>play(c)}>{c}</button>)}</div><button className="secondary-button" onClick={()=>setHand(h=>[...h,card()])}>یک ورق بکش</button></div>}
function Pictionary(){const canvas=useRef<HTMLCanvasElement>(null);const [word,setWord]=useState(drawWords[0]);const [drawing,setDrawing]=useState(false);const paint=(e:PointerEvent<HTMLCanvasElement>)=>{if(!drawing)return;const c=canvas.current;if(!c)return;const r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,ctx=c.getContext('2d')!;ctx.lineWidth=6;ctx.lineCap='round';ctx.lineTo(x,y);ctx.stroke();ctx.beginPath();ctx.moveTo(x,y)};const clear=()=>{const c=canvas.current;c?.getContext('2d')?.clearRect(0,0,c.width,c.height)};return <div className="arcade-center draw-stage"><p className="arcade-message">کلمهٔ این دور: <b>{word}</b></p><canvas ref={canvas} width="680" height="360" className="drawing-canvas" onPointerDown={e=>{setDrawing(true);paint(e)}} onPointerMove={paint} onPointerUp={()=>{setDrawing(false);canvas.current?.getContext('2d')?.beginPath()}}/><div className="inline-actions"><button className="secondary-button" onClick={clear}>پاک‌کردن</button><button className="primary-button" onClick={()=>{clear();setWord(drawWords[Math.floor(Math.random()*drawWords.length)])}}><Sparkles size={16}/>کلمهٔ بعدی</button></div></div>}
function Codenames(){const [revealed,setRevealed]=useState<number[]>([]);const words=useMemo(()=>[...codeWords].sort(()=>Math.random()-.5),[]);return <div className="arcade-center"><p className="arcade-message">تیم خودت را با یک سرنخ هدایت کن؛ کارت اشتباه را باز نکن.</p><div className="code-grid">{words.map((w,i)=><button className={`code-card ${revealed.includes(i)?i%5===0?'assassin':'revealed':''}`} key={w} onClick={()=>setRevealed(r=>[...r,i])}>{w}</button>)}</div></div>}
function Backgammon(){const [a,setA]=useState(0);const [b,setB]=useState(0);const [dice,setDice]=useState<[number,number]>([1,1]);const play=()=>{const d:[number,number]=[roll(),roll()];setDice(d);setA(v=>Math.min(15,v+d[0]));setB(v=>Math.min(15,v+d[1]))};return <div className="arcade-center"><div className="backgammon-board">{Array.from({length:24},(_,i)=><span key={i} className={i<a?'checker-a':i>23-b?'checker-b':''}>{i+1}</span>)}</div><p className="arcade-message">تاس: {dice[0]} و {dice[1]} — مهره‌های تو: {a}/۱۵</p><button className="primary-button" onClick={play}><Dice5 size={18}/>تاس بریز</button></div>}
function Hokm(){const [trump,setTrump]=useState('♥');const [hand,setHand]=useState(()=>Array.from({length:13},card));const [tricks,setTricks]=useState(0);return <div className="arcade-center hokm-stage"><p className="arcade-message">حکم این دور: <b className="trump">{trump}</b> — دست‌های برده: {tricks}</p><div className="uno-hand">{hand.map((c,i)=><button className="uno-card" key={`${c}${i}`} onClick={()=>{setHand(h=>h.filter(x=>x!==c));setTricks(t=>t+1)}}>{c}</button>)}</div><div className="inline-actions">{suits.map(s=><button className="secondary-button" key={s} onClick={()=>setTrump(s)}>{s}</button>)}</div><p className="observer-note"><Users size={15}/>چهار نفره؛ در نسخهٔ آنلاین، دست هر بازیکن خصوصی باقی می‌ماند.</p></div>}
