begin;

-- Truth-or-Dare prompts and room-local host-authored prompts are never accepted from game clients.
create table if not exists public.pp_truth_dare_prompts (
  id bigint generated by default as identity primary key,
  room_id uuid references public.pp_rooms(id) on delete cascade,
  choice text not null check (choice in ('truth','dare')),
  category text not null check (category in ('fun','friends','extreme','spicy')),
  text_fa text not null check (char_length(btrim(text_fa)) between 8 and 280),
  text_en text not null check (char_length(btrim(text_en)) between 8 and 280),
  created_by uuid references public.pp_profiles(id) on delete set null,
  is_builtin boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists pp_truth_dare_prompts_room_category_idx on public.pp_truth_dare_prompts(room_id,category,choice);
alter table public.pp_truth_dare_prompts enable row level security;
revoke all on public.pp_truth_dare_prompts from public, anon, authenticated;

create table if not exists public.pp_truth_dare_round_results (
  session_id uuid not null references public.pp_game_sessions(id) on delete cascade,
  round_no integer not null check (round_no > 0),
  player_id uuid not null references public.pp_profiles(id) on delete cascade,
  choice text not null check (choice in ('truth','dare')),
  prompt_id bigint references public.pp_truth_dare_prompts(id) on delete set null,
  completed boolean not null default false,
  passed boolean not null default false,
  created_at timestamptz not null default now(),
  primary key(session_id,round_no)
);
create table if not exists public.pp_truth_dare_ratings (
  session_id uuid not null,
  round_no integer not null,
  rater_id uuid not null references public.pp_profiles(id) on delete cascade,
  score smallint not null check (score between 1 and 5),
  created_at timestamptz not null default now(),
  primary key(session_id,round_no,rater_id),
  foreign key(session_id,round_no) references public.pp_truth_dare_round_results(session_id,round_no) on delete cascade
);
alter table public.pp_truth_dare_round_results enable row level security;
alter table public.pp_truth_dare_ratings enable row level security;
revoke all on public.pp_truth_dare_round_results,public.pp_truth_dare_ratings from public,anon,authenticated;

create or replace function public.partyplay_truth_dare_prompt_safe(p_text text,p_strict boolean default true)
returns boolean language plpgsql immutable security invoker set search_path=public as $$
declare v_text text := lower(btrim(coalesce(p_text,'')));
begin
  if char_length(v_text)<8 or char_length(v_text)>280 then return false; end if;
  if v_text ~* '(sex|sexual|nude|naked|porn|drug|alcohol|weapon|suicide|self.?harm|password|passcode|credit.?card|phone.?number|address|stalk|harass|touch|blindfold|hurt|dangerous|threat|برهنه|رابطه جنسی|مواد مخدر|الکل|خودکشی|خودآزاری|رمز عبور|شماره تلفن|آدرس|تعقیب|آزار|لمس|آسیب|خطرناک)' then return false; end if;
  if p_strict and v_text ~* '(secret|private|phone|contact|social media|message a stranger|رازی که|خصوصی|مخاطبین|شبکه اجتماعی|شماره)' then return false; end if;
  return true;
end;
$$;

insert into public.pp_truth_dare_prompts(choice,category,text_fa,text_en,is_builtin) values
('truth','fun','اگر می‌توانستی یک مهارت تازه را فوری یاد بگیری، چه بود؟','If you could instantly learn one new skill, what would it be?',true),
('truth','fun','کدام آهنگ همیشه حالت را بهتر می‌کند؟','Which song always lifts your mood?',true),
('truth','fun','خنده‌دارترین چیزی که اخیراً دیدی چه بود؟','What is the funniest thing you saw recently?',true),
('truth','fun','برای یک روز نامرئی بودن را چطور می‌گذراندی؟','How would you spend one day invisible?',true),
('truth','fun','اگر یک ابرقدرت داشتی، کدام را انتخاب می‌کردی؟','If you had one superpower, which would you choose?',true),
('truth','fun','کدام خوراکی را می‌توانی هر روز بخوری؟','What food could you eat every day?',true),
('truth','friends','اولین برداشتی که از دوست سمت راستت داشتی چه بود؟','What was your first impression of the friend on your right?',true),
('truth','friends','کدام خاطرهٔ گروهی را دوست داری دوباره تجربه کنی؟','Which group memory would you like to relive?',true),
('truth','friends','از کدام ویژگی دوستت بیشتر قدردانی می‌کنی؟','Which quality do you appreciate most in a friend?',true),
('truth','friends','چه چیزی باعث می‌شود کنار دوستانت احساس راحتی کنی؟','What helps you feel comfortable around friends?',true),
('truth','friends','چه سرگرمی‌ای را دوست داری با این گروه امتحان کنی؟','What hobby would you like to try with this group?',true),
('truth','extreme','یک تصمیم سخت که از آن چیز مهمی یاد گرفتی چه بود؟','What is a tough decision that taught you something important?',true),
('truth','extreme','کدام ترس کوچک را دوست داری با آمادگی بر آن غلبه کنی؟','What small fear would you like to work through at your own pace?',true),
('truth','extreme','اگر یک عادت را تغییر می‌دادی، کدام را انتخاب می‌کردی؟','If you could change one habit, which would you choose?',true),
('truth','spicy','ایده‌آل‌ترین قرار یا دورهمی دونفره از نظر تو چیست؟','What would your idea of a perfect date or one-on-one hangout be?',true),
('truth','spicy','کدام تعریف محترمانه بیشتر خوشحالت می‌کند؟','What respectful compliment makes you happiest?',true),
('dare','fun','یک حیوان خیالی را با صدا و حرکت اجرا کن تا گروه حدس بزند.','Act out an imaginary animal with sounds and gestures for the group to guess.',true),
('dare','fun','یک رقص خنده‌دار و بی‌خطر به مدت ده ثانیه اجرا کن.','Do a silly, safe dance for ten seconds.',true),
('dare','fun','یک خبر ساختگی و خنده‌دار دربارهٔ یک سیارهٔ خیالی اعلام کن.','Announce a silly fake news story about an imaginary planet.',true),
('dare','fun','یک شعر کوتاه دربارهٔ خوراکی محبوبت بساز.','Make up a short poem about your favorite snack.',true),
('dare','fun','تا نوبت بعدی مثل ربات حرف بزن؛ هر زمان خواستی می‌توانی رد کنی.','Talk like a robot until the next turn; you may pass whenever you like.',true),
('dare','friends','به یک دوست در گروه یک تعریف مهربانانه و مشخص بگو.','Give a friend in the group a kind, specific compliment.',true),
('dare','friends','یک خاطرهٔ خنده‌دار و بی‌حساسیت از خودت تعریف کن.','Tell a funny, low-stakes story about yourself.',true),
('dare','friends','با گروه یک شعار کوتاه و بامزه بساز.','Invent a short, silly team slogan with the group.',true),
('dare','friends','یک حرکت دست برای سلام گروهی طراحی کن.','Create a simple group greeting gesture.',true),
('dare','extreme','یک اجرای نمایشی ده‌ثانیه‌ای از قهرمان خیالی مورد علاقه‌ات انجام بده.','Give a ten-second dramatic performance as your favorite fictional hero.',true),
('dare','extreme','یک داستان کوتاه را فقط با حالت چهره تعریف کن.','Tell a tiny story using only facial expressions.',true),
('dare','extreme','یک آهنگ آشنا را با صدای اپرا بخوان؛ زمزمه هم قبول است.','Sing a familiar tune in an opera voice; humming counts too.',true),
('dare','extreme','به انتخاب خودت یک استعداد بامزه را به گروه نشان بده.','Show the group a funny talent of your choice.',true),
('dare','spicy','یک جملهٔ شروع گفت‌وگوی بامزه و محترمانه برای قرار خیالی بساز.','Invent a funny, respectful conversation opener for an imaginary date.',true),
('dare','spicy','برای یک شخصیت خیالی یک پیام تحسین‌آمیز و محترمانه بنویس.','Write a respectful, complimentary note for a fictional character.',true)
on conflict do nothing;

create or replace function public.partyplay_create_truth_dare_room(p_name text,p_capacity smallint,p_settings jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room jsonb; v_room_id uuid; v_categories text[]; v_category text; v_line text; v_choice text; v_prompt text; v_count integer:=0; v_strict boolean:=true;
begin
  if auth.uid() is null then perform public.partyplay_game_error('NOT_AUTHENTICATED'); end if;
  if p_capacity is null or p_capacity<2 or p_capacity>12 then perform public.partyplay_game_error('INVALID_CAPACITY'); end if;
  select array_agg(x) into v_categories from jsonb_array_elements_text(case when jsonb_typeof(p_settings->'categories')='array' then p_settings->'categories' else '["fun","friends","extreme"]'::jsonb end) x where x in ('fun','friends','extreme','spicy');
  if coalesce(cardinality(v_categories),0)=0 then v_categories:=array['fun','friends','extreme']; end if;
  v_strict:=case when lower(coalesce(p_settings->>'strict_filter','true')) in ('true','false') then lower(coalesce(p_settings->>'strict_filter','true'))::boolean else true end;
  v_room:=public.partyplay_create_room(p_name,'truth_or_dare',p_capacity);
  v_room_id:=(v_room->>'id')::uuid;
  update public.pp_rooms set settings=jsonb_build_object('enabled_categories',to_jsonb(v_categories),'strict_filter',v_strict,'passes_per_player',1) where id=v_room_id;
  for v_line in select value from jsonb_array_elements_text(case when jsonb_typeof(p_settings->'custom_prompts')='array' then p_settings->'custom_prompts' else '[]'::jsonb end) loop
    v_count:=v_count+1;
    if v_count>20 then perform public.partyplay_game_error('CUSTOM_PROMPT_LIMIT'); end if;
    v_choice:=case when lower(left(btrim(v_line),2))='d:' then 'dare' when lower(left(btrim(v_line),2))='t:' then 'truth' else null end;
    v_prompt:=btrim(substr(btrim(v_line),3));
    if v_choice is null or not public.partyplay_truth_dare_prompt_safe(v_prompt,v_strict) then perform public.partyplay_game_error('UNSAFE_CUSTOM_PROMPT'); end if;
    insert into public.pp_truth_dare_prompts(room_id,choice,category,text_fa,text_en,created_by,is_builtin)
    values(v_room_id,v_choice,v_categories[1],left(v_prompt,280),left(v_prompt,280),auth.uid(),false);
  end loop;
  return v_room;
end;
$$;

create or replace function public.partyplay_start_truth_dare(p_room_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room public.pp_rooms; v_session public.pp_game_sessions; v_players uuid[]; v_state jsonb; v_round integer:=1; v_categories jsonb;
begin
  if auth.uid() is null then perform public.partyplay_game_error('NOT_AUTHENTICATED'); end if;
  select * into v_room from public.pp_rooms where id=p_room_id for update;
  if not found then perform public.partyplay_game_error('ROOM_NOT_FOUND'); end if;
  if v_room.host_id<>auth.uid() then perform public.partyplay_game_error('NOT_HOST'); end if;
  if v_room.game_type<>'truth_or_dare' then perform public.partyplay_game_error('INVALID_GAME'); end if;
  if v_room.capacity<2 or v_room.capacity>12 then perform public.partyplay_game_error('INVALID_CAPACITY'); end if;
  v_players:=public.partyplay_truth_dare_random_cycle(v_room.id);
  if coalesce(array_length(v_players,1),0)<2 then perform public.partyplay_game_error('NEED_TWO_PLAYERS'); end if;
  v_categories:=coalesce(v_room.settings->'enabled_categories','["fun","friends","extreme"]'::jsonb);
  if jsonb_typeof(v_categories)<>'array' or jsonb_array_length(v_categories)=0 then v_categories:='["fun","friends","extreme"]'::jsonb; end if;
  if not exists(select 1 from public.pp_truth_dare_prompts p where p.room_id is null or p.room_id=v_room.id) then perform public.partyplay_game_error('NO_SAFE_PROMPTS'); end if;
  select * into v_session from public.pp_game_sessions where room_id=v_room.id for update;
  if found and v_session.status='running' then return public.partyplay_session_payload(v_session); end if;
  if found then v_round:=v_session.round_no+1; end if;
  v_state:=jsonb_build_object('phase','choosing','cycle_player_ids',to_jsonb(v_players),'cycle_index',0,'selected',null,'chat_closes_at',null,'enabled_categories',v_categories,'passes_used','{}'::jsonb);
  if found then
    update public.pp_game_sessions set game_type='truth_or_dare',status='running',round_no=v_round,state=v_state,turn_user_id=v_players[1],winner_id=null,version=0,finished_at=null where id=v_session.id returning * into v_session;
  else
    insert into public.pp_game_sessions(room_id,game_type,round_no,status,state,turn_user_id,version) values(v_room.id,'truth_or_dare',v_round,'running',v_state,v_players[1],0) returning * into v_session;
  end if;
  update public.pp_rooms set status='playing',started_at=now(),finished_at=null where id=v_room.id;
  insert into public.pp_game_events(session_id,actor_id,sequence_no,event_type,payload) values(v_session.id,auth.uid(),v_session.version,'truth_dare_started',jsonb_build_object('round_no',v_session.round_no)) on conflict(session_id,sequence_no) do nothing;
  return public.partyplay_session_payload(v_session);
end;
$$;

create or replace function public.partyplay_truth_dare_choose(p_session_id uuid,p_choice text,p_expected_version integer,p_command_id uuid default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_session public.pp_game_sessions; v_room public.pp_rooms; v_prompt public.pp_truth_dare_prompts; v_state jsonb; v_selected jsonb; v_categories text[]; v_strict boolean;
begin
  if auth.uid() is null then perform public.partyplay_game_error('NOT_AUTHENTICATED'); end if;
  if p_choice not in ('truth','dare') then perform public.partyplay_game_error('INVALID_CHOICE'); end if;
  select * into v_session from public.pp_game_sessions where id=p_session_id for update;
  if not found then perform public.partyplay_game_error('SESSION_NOT_FOUND'); end if;
  if p_command_id is not null and exists(select 1 from public.pp_game_events where session_id=v_session.id and client_command_id=p_command_id) then return public.partyplay_session_payload(v_session); end if;
  if v_session.game_type<>'truth_or_dare' or v_session.status<>'running' then perform public.partyplay_game_error('GAME_NOT_ACTIVE'); end if;
  if v_session.turn_user_id<>auth.uid() then perform public.partyplay_game_error('NOT_YOUR_TURN'); end if;
  if v_session.version<>p_expected_version then perform public.partyplay_game_error('CONFLICT'); end if;
  if coalesce(v_session.state->>'phase','')<>'choosing' then perform public.partyplay_game_error('CHOICE_ALREADY_MADE'); end if;
  select * into v_room from public.pp_rooms where id=v_session.room_id;
  select array_agg(value) into v_categories from jsonb_array_elements_text(v_session.state->'enabled_categories') value;
  v_strict:=coalesce((v_room.settings->>'strict_filter')::boolean,true);
  select * into v_prompt from public.pp_truth_dare_prompts p
  where p.choice=p_choice and p.category=any(v_categories) and (p.room_id is null or p.room_id=v_room.id)
    and public.partyplay_truth_dare_prompt_safe(p.text_fa,v_strict) and public.partyplay_truth_dare_prompt_safe(p.text_en,v_strict)
  order by random() limit 1;
  if not found then perform public.partyplay_game_error('NO_SAFE_PROMPTS'); end if;
  v_selected:=jsonb_build_object('player_id',auth.uid(),'choice',p_choice,'card_index',0,'prompt_id',v_prompt.id,'category',v_prompt.category,'text_fa',v_prompt.text_fa,'text_en',v_prompt.text_en);
  v_state:=jsonb_set(v_session.state,'{phase}','"revealed"'::jsonb,false);
  v_state:=jsonb_set(v_state,'{selected}',v_selected,false);
  update public.pp_game_sessions set state=v_state,version=version+1 where id=v_session.id returning * into v_session;
  insert into public.pp_truth_dare_round_results(session_id,round_no,player_id,choice,prompt_id) values(v_session.id,v_session.round_no,auth.uid(),p_choice,v_prompt.id) on conflict do nothing;
  insert into public.pp_game_events(session_id,actor_id,sequence_no,event_type,payload,client_command_id) values(v_session.id,auth.uid(),v_session.version,'truth_dare_choice',jsonb_build_object('choice',p_choice,'category',v_prompt.category,'round_no',v_session.round_no),p_command_id);
  return public.partyplay_session_payload(v_session);
end;
$$;

create or replace function public.partyplay_truth_dare_next_turn(p_session_id uuid,p_expected_version integer,p_command_id uuid default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_session public.pp_game_sessions; v_players uuid[]; v_index integer; v_next uuid; v_state jsonb;
begin
  if auth.uid() is null then perform public.partyplay_game_error('NOT_AUTHENTICATED'); end if;
  select * into v_session from public.pp_game_sessions where id=p_session_id for update;
  if not found then perform public.partyplay_game_error('SESSION_NOT_FOUND'); end if;
  if p_command_id is not null and exists(select 1 from public.pp_game_events where session_id=v_session.id and client_command_id=p_command_id) then return public.partyplay_session_payload(v_session); end if;
  if v_session.game_type<>'truth_or_dare' or v_session.status<>'running' then perform public.partyplay_game_error('GAME_NOT_ACTIVE'); end if;
  if v_session.turn_user_id<>auth.uid() then perform public.partyplay_game_error('NOT_YOUR_TURN'); end if;
  if v_session.version<>p_expected_version then perform public.partyplay_game_error('CONFLICT'); end if;
  if coalesce(v_session.state->>'phase','')<>'revealed' then perform public.partyplay_game_error('CARD_NOT_REVEALED'); end if;
  update public.pp_truth_dare_round_results set completed=true where session_id=v_session.id and round_no=v_session.round_no and player_id=auth.uid() and not passed;
  select array_agg(value::uuid) into v_players from jsonb_array_elements_text(v_session.state->'cycle_player_ids') value;
  v_index:=coalesce((v_session.state->>'cycle_index')::integer,0)+1;
  if v_index>=coalesce(array_length(v_players,1),0) then v_players:=public.partyplay_truth_dare_random_cycle(v_session.room_id); v_index:=0; end if;
  v_next:=v_players[v_index+1];
  v_state:=jsonb_set(v_session.state,'{phase}','"choosing"'::jsonb,false);
  v_state:=jsonb_set(v_state,'{cycle_player_ids}',to_jsonb(v_players),false);
  v_state:=jsonb_set(v_state,'{cycle_index}',to_jsonb(v_index),false);
  v_state:=jsonb_set(v_state,'{selected}','null'::jsonb,false);
  update public.pp_game_sessions set state=v_state,turn_user_id=v_next,round_no=round_no+1,version=version+1 where id=v_session.id returning * into v_session;
  insert into public.pp_game_events(session_id,actor_id,sequence_no,event_type,payload,client_command_id) values(v_session.id,auth.uid(),v_session.version,'truth_dare_next_turn',jsonb_build_object('round_no',v_session.round_no,'turn_user_id',v_next),p_command_id);
  return public.partyplay_session_payload(v_session);
end;
$$;

create or replace function public.partyplay_truth_dare_rate(p_session_id uuid,p_round_no integer,p_score smallint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_session public.pp_game_sessions; v_result public.pp_truth_dare_round_results;
begin
  if auth.uid() is null then perform public.partyplay_game_error('NOT_AUTHENTICATED'); end if;
  if p_score is null or p_score<1 or p_score>5 then perform public.partyplay_game_error('INVALID_RATING'); end if;
  select * into v_session from public.pp_game_sessions where id=p_session_id for update;
  if not found then perform public.partyplay_game_error('SESSION_NOT_FOUND'); end if;
  if v_session.status not in ('running','finished') or (v_session.status='finished' and now()>coalesce(nullif(v_session.state->>'chat_closes_at','')::timestamptz,now())) then perform public.partyplay_game_error('GAME_NOT_ACTIVE'); end if;
  if not exists(select 1 from public.pp_room_members where room_id=v_session.room_id and user_id=auth.uid() and role in ('host','player')) then perform public.partyplay_game_error('NOT_A_MEMBER'); end if;
  select * into v_result from public.pp_truth_dare_round_results where session_id=p_session_id and round_no=p_round_no;
  if not found then perform public.partyplay_game_error('ROUND_NOT_FOUND'); end if;
  if v_result.player_id=auth.uid() then perform public.partyplay_game_error('CANNOT_RATE_SELF'); end if;
  insert into public.pp_truth_dare_ratings(session_id,round_no,rater_id,score) values(p_session_id,p_round_no,auth.uid(),p_score)
  on conflict(session_id,round_no,rater_id) do update set score=excluded.score,created_at=now();
  update public.pp_game_sessions set state=jsonb_set(state,'{rating_revision}',to_jsonb(coalesce((state->>'rating_revision')::integer,0)+1),true),version=version+1 where id=v_session.id returning * into v_session;
  return public.partyplay_session_payload(v_session);
end;
$$;

create or replace function public.partyplay_truth_dare_pass(p_session_id uuid,p_expected_version integer,p_command_id uuid default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_session public.pp_game_sessions; v_players uuid[]; v_index integer; v_next uuid; v_state jsonb; v_key text:=auth.uid()::text; v_used integer;
begin
  if auth.uid() is null then perform public.partyplay_game_error('NOT_AUTHENTICATED'); end if;
  select * into v_session from public.pp_game_sessions where id=p_session_id for update;
  if not found then perform public.partyplay_game_error('SESSION_NOT_FOUND'); end if;
  if p_command_id is not null and exists(select 1 from public.pp_game_events where session_id=v_session.id and client_command_id=p_command_id) then return public.partyplay_session_payload(v_session); end if;
  if v_session.game_type<>'truth_or_dare' or v_session.status<>'running' or v_session.turn_user_id<>auth.uid() then perform public.partyplay_game_error('NOT_YOUR_TURN'); end if;
  if v_session.version<>p_expected_version then perform public.partyplay_game_error('CONFLICT'); end if;
  if coalesce(v_session.state->>'phase','')<>'revealed' then perform public.partyplay_game_error('CARD_NOT_REVEALED'); end if;
  v_used:=coalesce((v_session.state->'passes_used'->>v_key)::integer,0);
  if v_used>=1 then perform public.partyplay_game_error('PASS_LIMIT_REACHED'); end if;
  update public.pp_truth_dare_round_results set passed=true where session_id=v_session.id and round_no=v_session.round_no and player_id=auth.uid();
  select array_agg(value::uuid) into v_players from jsonb_array_elements_text(v_session.state->'cycle_player_ids') value;
  v_index:=coalesce((v_session.state->>'cycle_index')::integer,0)+1;
  if v_index>=coalesce(array_length(v_players,1),0) then v_players:=public.partyplay_truth_dare_random_cycle(v_session.room_id); v_index:=0; end if;
  v_next:=v_players[v_index+1];
  v_state:=jsonb_set(v_session.state,'{phase}','"choosing"'::jsonb,false);
  v_state:=jsonb_set(v_state,'{cycle_player_ids}',to_jsonb(v_players),false);
  v_state:=jsonb_set(v_state,'{cycle_index}',to_jsonb(v_index),false);
  v_state:=jsonb_set(v_state,'{selected}','null'::jsonb,false);
  v_state:=jsonb_set(v_state,array['passes_used',v_key],to_jsonb(v_used+1),true);
  update public.pp_game_sessions set state=v_state,turn_user_id=v_next,round_no=round_no+1,version=version+1 where id=v_session.id returning * into v_session;
  insert into public.pp_game_events(session_id,actor_id,sequence_no,event_type,payload,client_command_id) values(v_session.id,auth.uid(),v_session.version,'truth_dare_pass',jsonb_build_object('round_no',v_session.round_no),p_command_id);
  return public.partyplay_session_payload(v_session);
end;
$$;

create or replace function public.partyplay_truth_dare_scoreboard(p_session_id uuid)
returns table(player_id uuid,display_name text,average_rating numeric,rating_count integer,completed_turns integer,passes_used integer)
language plpgsql stable security definer set search_path=public as $$
begin
  if auth.uid() is null or not exists(select 1 from public.pp_room_members m join public.pp_game_sessions s on s.room_id=m.room_id where s.id=p_session_id and m.user_id=auth.uid() and m.role in ('host','player')) then perform public.partyplay_game_error('NOT_A_MEMBER'); end if;
  return query select m.user_id,p.display_name,coalesce(round(avg(r.score)::numeric,1),0),count(r.rater_id)::integer,
    count(distinct case when rr.completed and not rr.passed then rr.round_no end)::integer,
    coalesce((s.state->'passes_used'->>m.user_id::text)::integer,0)
  from public.pp_game_sessions s join public.pp_room_members m on m.room_id=s.room_id and m.role in ('host','player') join public.pp_profiles p on p.id=m.user_id
  left join public.pp_truth_dare_round_results rr on rr.session_id=s.id and rr.player_id=m.user_id
  left join public.pp_truth_dare_ratings r on r.session_id=rr.session_id and r.round_no=rr.round_no
  where s.id=p_session_id group by m.user_id,p.display_name,s.state order by coalesce(round(avg(r.score)::numeric,1),0) desc,m.display_name;
end;
$$;

revoke all on function public.partyplay_truth_dare_prompt_safe(text,boolean) from public;
revoke all on function public.partyplay_create_truth_dare_room(text,smallint,jsonb) from public;
revoke all on function public.partyplay_truth_dare_rate(uuid,integer,smallint) from public;
revoke all on function public.partyplay_truth_dare_pass(uuid,integer,uuid) from public;
revoke all on function public.partyplay_truth_dare_scoreboard(uuid) from public;
grant execute on function public.partyplay_create_truth_dare_room(text,smallint,jsonb) to authenticated;
grant execute on function public.partyplay_truth_dare_rate(uuid,integer,smallint) to authenticated;
grant execute on function public.partyplay_truth_dare_pass(uuid,integer,uuid) to authenticated;
grant execute on function public.partyplay_truth_dare_scoreboard(uuid) to authenticated;
notify pgrst,'reload schema';
commit;
